#Direct to Bosun
#Host = "localhost:8070"

#Send to tsdbrelay. Use TSDBRELAY_OPTS environment variable for forwarding options
Host = "172.29.231.177:4243"

BatchSize = 5000

#Monitoring of hbase inside the container
HadoopHost = "localhost:16010"

[Tags]
  uid = "20"
  


#Redis or ledis based external counters. See https://godoc.org/bosun.org/cmd/tsdbrelay

	
[[SNMP]]
  Community = "c3560"
  Host = "172.29.231.1"
  MIBs = ["cisco"]

[MIBs]
  [MIBs.cisco] #can name anything you want
    BaseOid = "1.3.6.1.2.1.2.2.1" # common base for all metrics in this mib

    # simple, single key metrics
    [[MIBs.cisco.Metrics]]
      Metric = "cisco.cpu"
      Oid = ".1.1"
      Unit = "percent"
      RateType = "gauge"
      Description = "cpu percent used by this device"


		
[[ICMP]]
  Host = "172.29.225.1"
[[ICMP]]
  Host = "172.29.231.70"		